const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, 'images');
const OUTPUT_FILE = path.join(__dirname, 'js', 'images-data.js');

function scanDirectory(dir, fileList = []) {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    if (file.startsWith('.')) continue; // ignore hidden files
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      scanDirectory(filePath, fileList);
    } else {
      if (/\.(jpg|jpeg|png|webp|gif)$/i.test(file)) {
        // We want the relative path from the project root
        fileList.push(path.relative(__dirname, filePath).replace(/\\/g, '/'));
      }
    }
  }
  return fileList;
}

function updateScript() {
  try {
    const images = scanDirectory(IMAGES_DIR);
    const content = `// This file is auto-generated by watch_images.js\nwindow.DYNAMIC_IMAGES = ${JSON.stringify(images, null, 2)};\n`;
    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`[${new Date().toLocaleTimeString()}] images-data.js updated (${images.length} images found)`);
  } catch (err) {
    console.error('Error updating images-data.js:', err);
  }
}

// Initial scan
updateScript();

// Watch for changes via robust polling (fixes macOS fs.watch dropping events)
let lastImagesJSON = "";
setInterval(() => {
  const images = scanDirectory(IMAGES_DIR);
  const newJSON = JSON.stringify(images);
  if (newJSON !== lastImagesJSON) {
    lastImagesJSON = newJSON;
    const content = `// This file is auto-generated by watch_images.js\nwindow.DYNAMIC_IMAGES = ${JSON.stringify(images, null, 2)};\n`;
    try {
      fs.writeFileSync(OUTPUT_FILE, content);
      console.log(`[${new Date().toLocaleTimeString()}] images-data.js updated (${images.length} images found)`);
    } catch (err) {}
  }
}, 1000);

console.log(`Watching for changes in ${IMAGES_DIR} (Polling mode)...\nI am running in the background for you.`);
